### PR TITLE
Updating paper status

### PR DESCRIPTION
**Pull request by ebagdasa**
Thank you for the great work of keeping it up to date!

### CODE REVIEW

**Comment by ebagdasa** [comment]
Not sure if what we did was poisoning though :D , but happy to move it to other places.

**Review by THUYimingLi — APPROVED** [review]

**Comment by THUYimingLi** [comment]
Thank you for your recognition and congrats on your work been accepted by Oakland!!!

**Comment by THUYimingLi** [comment]
> Not sure if what we did was poisoning though :D , but happy to move it to other places.

BTW, I think your paper is more about NLP instead of the image classification. Accordingly, I move your paper to the NLP track. Feel free to tell me if there is any misunderstanding :)

**Comment by ebagdasa** [comment]
thanks a lot, definitely NLP!

**Pull request merged**
